# Exported from Render on 2024-11-05T02:47:11Z
services:
- type: web
  name: wine-api-fiap
  runtime: python
  repo: https://github.com/VictorJSSantos/Modulo-1
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
version: "1"
